### ISSUE TITLE
Cannot read property 'urlTransformer' of undefined

### ISSUE THREAD

**Issue by alsoicode** [jbellsey/aurelia-cached-getter#1]
When using the cached-getter with Aurelia 0.16.0:

```
import {HttpCachedGetter} from 'jbellsey/aurelia-cached-getter';

export class Api {
    constructor() {
        this.httpCachedGet = (new HttpCachedGetter()).configure(x => {
            x.withBaseUrl('http://localhost:8000/api/');
        });
    };
}
```

I get the following traceback:

```
ERROR [app-router] Error: Error instantiating Api. Check the inner error for details.
------------------------------------------------
inner error: TypeError: Cannot read property 'urlTransformer' of undefined
    at new HttpCachedGetter (http://localhost:9000/jspm_packages/github/jbellsey/aurelia-cached-getter@master/http-cached-getter.js:15:38)
    at new Api (http://localhost:9000/dist/api.js:27:42)
    at Object.n.construct (http://localhost:9000/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:1980:21)
    at ClassActivator.invoke (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.10.1/aurelia-dependency-injection.js:186:22)
    at Container.invoke (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.10.1/aurelia-dependency-injection.js:403:31)
    at Array.<anonymous> (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.10.1/aurelia-dependency-injection.js:272:44)
    at Container.get (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.10.1/aurelia-dependency-injection.js:339:22)
    at Container.get (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.10.1/aurelia-dependency-injection.js:333:28)
    at Container.invoke (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.10.1/aurelia-dependency-injection.js:396:26)
    at Array.<anonymous> (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.10.1/aurelia-dependency-injection.js:272:44)
    at new HttpCachedGetter (http://localhost:9000/jspm_packages/github/jbellsey/aurelia-cached-getter@master/http-cached-getter.js:15:38)
    at new Api (http://localhost:9000/dist/api.js:27:42)
    at Object.n.construct (http://localhost:9000/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:1980:21)
    at ClassActivator.invoke (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.10.1/aurelia-dependency-injection.js:186:22)
    at Container.invoke (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.10.1/aurelia-dependency-injection.js:403:31)
    at Array.<anonymous> (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.10.1/aurelia-dependency-injection.js:272:44)
    at Container.get (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.10.1/aurelia-dependency-injection.js:339:22)
    at Container.get (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.10.1/aurelia-dependency-injection.js:333:28)
    at Container.invoke (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.10.1/aurelia-dependency-injection.js:396:26)
    at Array.<anonymous> (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.10.1/aurelia-dependency-injection.js:272:44)
    at new AggregateError (http://localhost:9000/jspm_packages/github/aurelia/logging@0.7.0/aurelia-logging.js:24:13)
    at Container.invoke (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.10.1/aurelia-dependency-injection.js:413:15)
    at Array.<anonymous> (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.10.1/aurelia-dependency-injection.js:272:44)
    at Container.get (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.10.1/aurelia-dependency-injection.js:339:22)
    at Container.get (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.10.1/aurelia-dependency-injection.js:333:28)
    at Container.invoke (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.10.1/aurelia-dependency-injection.js:396:26)
    at Array.<anonymous> (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.10.1/aurelia-dependency-injection.js:272:44)
    at Container.get (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.10.1/aurelia-dependency-injection.js:329:24)
    at http://localhost:9000/jspm_packages/github/aurelia/templating@0.15.3/aurelia-templating.js:3684:75
    at f (http://localhost:9000/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:1415:56)error @ aurelia-logging-console.js:62log @ aurelia-logging.js:56error @ aurelia-logging.js:89processResult @ aurelia-router.js:1726(anonymous function) @ aurelia-router.js:1582f @ shim.min.js:1415(anonymous function) @ shim.min.js:1423b.exports @ shim.min.js:453b.(anonymous function) @ shim.min.js:1625f @ shim.min.js:1596q @ shim.min.js:1600
```

**Comment by jbellsey** [comment]
I suspect this is due to a Babel setting that I have turned on. Should be fixed tomorrow.

In the meantime, you may be able to work around this by passing an empty object to the constructor:

```
new HttpCachedGetter({})
```

**Comment by alsoicode** [comment]
Thanks!
